### ISSUE TITLE
http resolution for packages affected by 1/6/18 incident

### ISSUE THREAD

**Issue by billyjanitsch** [npm/registry-issue-archive#260]
Packages that were affected by the 1/6/18 incident seem to now resolve over http rather than https.

For example, `create-error-class` was [affected](https://github.com/floatdrop/create-error-class/issues/5) by the incident, whereas `react` was not.

```sh
$ mkdir foo && cd foo
$ npm cache clear -f
$ npm i create-error-class react
$ cat package-lock.json
```

For some reason, `create-error-class` and its dependencies now resolve over http:
```json
"capture-stack-trace": {
  "version": "1.0.0",
  "resolved": "http://registry.npmjs.org/capture-stack-trace/-/capture-stack-trace-1.0.0.tgz",
  "integrity": "sha1-Sm+gc5nCa7pH8LJJa00PtAjFVQ0="
},
"create-error-class": {
  "version": "3.0.2",
  "resolved": "http://registry.npmjs.org/create-error-class/-/create-error-class-3.0.2.tgz",
  "integrity": "sha1-Br56vvlHo/FKMP1hBnHUAbyot7Y=",
  "requires": {
    "capture-stack-trace": "1.0.0"
  }
},
```

Whereas `react` and its dependencies correctly resolve over https:

```json
"prop-types": {
  "version": "15.6.0",
  "resolved": "https://registry.npmjs.org/prop-types/-/prop-types-15.6.0.tgz",
  "integrity": "sha1-zq8IMCL8RrSjX2nhPvda7Q1jmFY=",
  "requires": {
    "fbjs": "0.8.16",
    "loose-envify": "1.3.1",
    "object-assign": "4.1.1"
  }
},
"react": {
  "version": "16.2.0",
  "resolved": "https://registry.npmjs.org/react/-/react-16.2.0.tgz",
  "integrity": "sha512-ZmIomM7EE1DvPEnSFAHZn9Vs9zJl5A9H7el0EGTE6ZbW9FKe/14IYAlPbC8iH25YarEQxZL+E8VW7Mi7kfQrDQ==",
  "requires": {
    "fbjs": "0.8.16",
    "loose-envify": "1.3.1",
    "object-assign": "4.1.1",
    "prop-types": "15.6.0"
  }
},
```

**Comment by soldair** [comment]
thanks. we'll take a look.
we verify the checksum so there is no risk of compromise but it should be https.

**Comment by soldair** [comment]
not sure how it got in this state but i triggered reprocessing and the url was fixed =)

**Comment by billyjanitsch** [comment]
Thanks @soldair ❤️

**Comment by billyjanitsch** [comment]
Looks like this is still an issue with the `co-with-promise` package.

**Comment by soldair** [comment]
fixed. small trick if you feel so inclined.
npm star package && npm unstar packagename
causes all of the machinery to run to update the metadata and flush caches. This is how i fixed these because it easier than getting under the the hood of the thing.

**Comment by billyjanitsch** [comment]
Hey @soldair, I've noticed this happening again (with `cacache` and `pinkie-promise`). Your star/unstar trick worked to fix them, but I just wanted to let you know that the registry still seems to be doing this occasionally.

**Comment by soldair** [comment]
thanks! we changed some backends around again and a couple bugs ran out sorry about that.
