### ISSUE TITLE
Fetching a large package fails

### ISSUE THREAD

**Issue by GabrielCastro** [npm/registry-issue-archive#287]
The registry is failing to deliver large npm packages.

We ran into the following 2 issues (dependent on the version of npm) [npm#19997](https://github.com/npm/npm/issues/19997) and [npm#19994]. After some digging we discovered the root cause to be with the registry delivering a truncated tarball. 

The simplest reproduction:

```
gabe@a85a303bbbdd:~# curl https://registry.npmjs.org/@[REDACTED]/[REDACTED]/-/[REDACTED]-0.9.3.tgz -H 'Authorization: Bearer [REDACTED]' -vL | wc -c

* Connected to registry.npmjs.org (151.101.40.162) port 443 (#0)
> GET /@[REDACTED]/[REDACTED]/-/[REDACTED]-0.9.3.tgz HTTP/1.1
> User-Agent: curl/7.38.0
> Host: registry.npmjs.org
> Accept: */*
> Authorization: Bearer [REDACTED]
>
< HTTP/1.1 200 OK
< content-type: application/octet-stream
* Server AmazonS3 is not blacklisted
< server: AmazonS3
< etag: "4ac2421d-74b3cc3"
< last-modified: Tue, 29 Sep 2009 17:21:33 GMT
< age: 0
< via: 1.1 varnish (Varnish/5.2)
< accept-ranges: bytes
< Cache-Control: max-age=0
< Content-Length: 122371267
< Accept-Ranges: bytes
< Date: Thu, 08 Mar 2018 18:20:41 GMT
< Via: 1.1 varnish
< Connection: keep-alive
< X-Served-By: cache-sjc3625-SJC
< X-Cache: MISS
< X-Cache-Hits: 0
< X-Timer: S1520533241.398722,VS0,VE156
<
* transfer closed with 61085260 bytes remaining to read
* Closing connection 0
curl: (18) transfer closed with 61085260 bytes remaining to read

61286007
```

In this case the actual size of the package is `122371267 bytes (122mb)` which is correctly reported in the `Content-Length` header but only  `61286007 bytes (61 mb)` is being transferred before the connection is closed.

**Comment by soldair** [comment]
thanks for the ping @GabrielCastro. im looking into this now. please contact support@npmjs.com with your npm-debug.log so we can let you know when you're resolved.

**Comment by soldair** [comment]
hey this should be resolved now. if you run into this again please notify support.

**Comment by lvthillo** [comment]
Do we need to perform something? We are still facing issue https://github.com/npm/npm/issues/19997 sometimes

**Comment by jeffora** [comment]
@soldair We're seeing similar behavior, but the package is only 8.2mb. The download is truncated at varying lengths, but `npm` doesn't error on install during download - only during verification check.

**Comment by soldair** [comment]
Hey Jeff I'll look into it asap. If you haven't already please email support with the tarball or package and version that's failing.
